export const adminNavItems = [
  { icon: '📊', label: 'Dashboard', to: '/admin' },
  { icon: '👥', label: 'Usuarios', to: '/admin/users' },
  { icon: '🤝', label: 'Clientes', to: '/admin/clients' },
  { icon: '🚚', label: 'Conductores', to: '/admin/drivers' },
  { icon: '🛡️', label: 'Moderadores', to: '/admin/moderators' },
  { icon: '🛣️', label: 'Viajes', to: '/admin/trips' },
  { icon: '💰', label: 'Ganancias', to: '/admin/earnings' },
  { icon: '📈', label: 'Comisiones', to: '/admin/commissions' },
  { icon: '✅', label: 'Verificaciones', to: '/admin/verifications' },
  { icon: '📄', label: 'Reportes', to: '/admin/reports' },
  { icon: '⚖️', label: 'Disputas', to: '/admin/disputes' },
  { icon: '🚨', label: 'Emergencias', to: '/admin/emergencies' },
  { icon: '❌', label: 'Cancelaciones', to: '/admin/cancellation-requests' },
  { icon: '💳', label: 'Pagos', to: '/admin/payments' },
  { icon: '📢', label: 'Comunicados', to: '/admin/comunicados' },
  { icon: '📊', label: 'Encuestas', to: '/admin/encuestas' },
  { icon: '📌', label: 'Avisos', to: '/admin/avisos' },
  { icon: '💬', label: 'Conversatorio', to: '/admin/conversations' },
  { icon: '🗒️', label: 'Reportes Moderador', to: '/admin/moderator-reports' },
  { icon: '⚙️', label: 'Configuración', to: '/admin/config' },
  { icon: '📦', label: 'Backups', to: '/admin/backups' },
  { icon: '👤', label: 'Mi Perfil', to: '/admin/profile' },
];

export const moderatorNavItems = [
  { icon: '📊', label: 'Dashboard', to: '/moderator' },
  { icon: '🛣️', label: 'Viajes', to: '/moderator/trips' },
  { icon: '🚨', label: 'Emergencias', to: '/moderator/emergencies' },
  { icon: '👥', label: 'Conductores', to: '/moderator/drivers' },
  { icon: '😴', label: 'Inactivos', to: '/moderator/drivers/inactive' },
  { icon: '🤝', label: 'Compañeros', to: '/moderator/companeros' },
  { icon: '💬', label: 'Conversatorio', to: '/moderator/conversations' },
  { icon: '📌', label: 'Avisos', to: '/moderator/avisos' },
  { icon: '📢', label: 'Comunicados', to: '/moderator/comunicados' },
  { icon: '📊', label: 'Encuestas', to: '/moderator/encuestas' },
  { icon: '🔔', label: 'Notificaciones', to: '/moderator/reports' },
  { icon: '👤', label: 'Mi Perfil', to: '/moderator/profile' },
];